### ISSUE TITLE
Add option to save internal variables during SI-simulation

### ISSUE THREAD

**Issue by franksh** [benmaier/tacoma#18]
Currently only some variables of the SI-simulation are saved and accessible via the Python-API: The time (SI.time), number of infected (SI.I) and a list of susceptible-infected contacts (SI.SI).

It would be nice to have to option to save more detailed internal variables, such as a list of infection events, such that for instance information on transmission chains is extractable. These variables are currently computed during the simulation but not kept for memory efficiency.

The option could be added to the `tc.SI()` interface as a flag `save_internal_variables=True/False`

**Comment by franksh** [comment]
I'm implementing the changes at the moment. I noticed that the actual memory demand of the new variable won't be big. At the moment the code saves the time when an event occurs, as well as the observables SI and I, which are each `vector <size_t>`. The new variable infection events will be of similar size. Should I still include the flag `save_infection_events` or just include it by default without the option to change?

**Comment by franksh** [comment]
Btw I noticed that the docstrings at https://github.com/benmaier/tacoma/blob/master/_tacoma/_tacoma.cpp#L1074 for `S, I` are not correct, same in the SIS model. I will fix them with this pull request.

**Comment by benmaier** [comment]
I thought about this and think that for standard simulations (analysis of prevalence curves) one would only need I (not even SI) and everything else should be unnecessary. For this reason I'd prefer the flag as not to clutter the result classes.

Granted following this logic SI should get an own flag, too ... but I'd rather think about it later and keep it like this for the moment.

Cheers for fixing the docstrings!
